import { z } from 'zod';
import { PARTNER_ROLES } from '@/service/apps/master-data/business-partner/roles';

// ─── Business Partner ───────────────────────────────────────────────────────
// A partner is identified by its CODE (BP-000001), which is generated by the
// sequence framework and never writable by a client — not by name or phone,
// both of which change over a relationship's life.

export const partnerRoleEnum = z.enum(PARTNER_ROLES);

const nullableString = (max: number) =>
    z.string().max(max).trim().optional().nullable();

export const businessPartnerAddressSchema = z.object({
    address_type: z.enum(['billing', 'shipping', 'both', 'other']).default('both'),
    label: nullableString(100),
    country: nullableString(100),
    province: nullableString(100),
    district: nullableString(100),
    commune: nullableString(100),
    street: z.string().trim().optional().nullable(),
    postal_code: nullableString(20),
    is_default_billing: z.boolean().optional(),
    is_default_shipping: z.boolean().optional(),
    is_active: z.boolean().default(true),
});

export const businessPartnerContactSchema = z.object({
    name: z.string().min(1, 'Contact name is required').max(200).trim(),
    position: nullableString(100),
    phone: nullableString(50),
    email: z.string().email('Invalid email').max(200).optional().nullable(),
    is_primary: z.boolean().default(false),
    notes: z.string().trim().optional().nullable(),
    is_active: z.boolean().default(true),
});

const partnerBase = {
    name: z.string().min(1, 'Partner name is required').max(200).trim(),
    company_name: nullableString(200),
    partner_kind: z.enum(['organization', 'individual']).default('organization'),
    phone: nullableString(50),
    phone_alt: nullableString(50),
    email: z.string().email('Invalid email').max(200).optional().nullable(),
    website: nullableString(200),
    tax_number: nullableString(50),
    vat_number: nullableString(50),
    registration_number: nullableString(50),
    credit_limit: z.number().min(0, 'Credit limit cannot be negative').optional().nullable(),
    payment_term_days: z.number().int().min(0).max(365).optional().nullable(),
    currency: z.string().length(3).default('USD'),
    notes: z.string().trim().optional().nullable(),
    is_active: z.boolean().default(true),
};

export const createBusinessPartnerSchema = z.object({
    ...partnerBase,
    roles: z.array(partnerRoleEnum).min(1, 'Select at least one role'),
    /** Optional primary address created alongside the partner. */
    address: businessPartnerAddressSchema.optional().nullable(),
});

export const updateBusinessPartnerSchema = z
    .object({
        ...partnerBase,
        roles: z.array(partnerRoleEnum).min(1, 'Select at least one role'),
    })
    .partial();

/**
 * The counter path: everything a cashier can be asked for mid-sale. Anything
 * richer belongs in Master Data, not in front of a queue.
 */
export const quickCreateBusinessPartnerSchema = z.object({
    name: z.string().min(1, 'Partner name is required').max(200).trim(),
    phone: nullableString(50),
    role: partnerRoleEnum.default('customer'),
    /** When false, a phone that already exists is an error instead of a reuse. */
    reuse_on_phone_match: z.boolean().default(true),
});

export const businessPartnerIdSchema = z.object({
    id: z.coerce.number().int().positive(),
});

export const partnerStatusSchema = z.object({
    is_active: z.boolean(),
});

export type CreateBusinessPartnerInput = z.infer<typeof createBusinessPartnerSchema>;
export type UpdateBusinessPartnerInput = z.infer<typeof updateBusinessPartnerSchema>;
export type QuickCreateBusinessPartnerInput = z.infer<
    typeof quickCreateBusinessPartnerSchema
>;
export type BusinessPartnerAddressInput = z.infer<typeof businessPartnerAddressSchema>;
export type BusinessPartnerContactInput = z.infer<typeof businessPartnerContactSchema>;