create table public.company (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  writed_at timestamp with time zone null,
  name character varying not null,
  domain character varying null,
  constraint company_pkey primary key (id),
  constraint company_name_key unique (name)
) TABLESPACE pg_default;


insert into public.company (name, domain) values ('Default Company', 'default');
insert into public.company (name, domain) values ('Acme Corporation', 'acme');
insert into public.company (name, domain) values ('Globex Corporation', 'globex');
insert into public.company (name, domain) values ('Initech', 'initech');


-- Links every auth user to a company
create table if not exists public.profiles (
    id         uuid   not null,
    company_id bigint null,
    full_name   text   null,
    avatar_url  text   null,
    created_at timestamp with time zone not null default now(),
    writed_at timestamp with time zone null,
    constraint profiles_pkey primary key (id),
    constraint profiles_id_fkey foreign key (id) references auth.users (id) on delete cascade,
    constraint profiles_company_id_fkey foreign key (company_id) references public.company (id) on delete set null
);


-- Create user_role reference / lookup table
create table public.roles (
    id          bigint generated by default as identity not null,
    name        text   not null,
    description text   null,
    created_at timestamp with time zone not null default now(),
    writed_at timestamp with time zone null,
    constraint roles_pkey primary key (id),
    constraint roles_name_key unique (name)
);

-- Seed the default roles
insert into public.roles (name, description) values
  ('super_admin', 'Super user with full system access'),
  ('admin',       'Administrator with management access'),
  ('staff',       'Regular staff member'),
  ('member',      'Basic member with limited access');


create table if not exists public.user_role (
    id         bigint generated by default as identity not null,
    user_id    uuid   not null references auth.users (id) on delete cascade,
    role_id    bigint not null references public.roles (id) on delete cascade,
    company_id bigint not null references public.company (id) on delete cascade,
    created_at timestamp with time zone not null default now(),
    writed_at timestamp with time zone null,
    constraint user_role_pkey primary key (id),
    constraint user_role_user_id_role_id_company_id_key unique (user_id, role_id, company_id)
);
create index if not exists user_role_user_id_idx on public.user_role (user_id);
create index if not exists user_role_role_id_idx on public.user_role (role_id);
create index if not exists user_role_company_id_idx on public.user_role (company_id);


create table if not exists public.modules (
    id         bigint generated by default as identity not null,
    key       text   not null,
    label     text   not null,
    path      text   not null,
    component text   not null,
    parent_id bigint null references public.modules (id) on delete cascade,
    icon     text   null,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    writed_at timestamp with time zone null,
    constraint modules_pkey primary key (id),
    constraint modules_key_key unique (key)
);


create table if not exists public.role_module_permission (
    id bigint generated by default as identity not null,
    role_id bigint not null references public.roles (id) on delete cascade,
    module_id bigint not null references public.modules (id) on delete cascade,
    can_view boolean not null default false,
    can_create boolean not null default false,
    can_update boolean not null default false,
    can_delete boolean not null default false,
    can_export boolean not null default false,
    created_at timestamp with time zone not null default now(),
    writed_at timestamp with time zone null,
    constraint role_module_permission_pkey primary key (id),
    constraint role_module_permission_role_id_module_id_key unique (role_id, module_id)
);
