create table public.company (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  writed_at timestamp with time zone null,
  name character varying not null,
  domain character varying null,
  constraint company_pkey primary key (id),
  constraint company_name_key unique (name)
) TABLESPACE pg_default;


insert into public.company (name, domain) values ('Default Company', 'default');
insert into public.company (name, domain) values ('Acme Corporation', 'acme');
insert into public.company (name, domain) values ('Globex Corporation', 'globex');
insert into public.company (name, domain) values ('Initech', 'initech');    
