-- ─────────────────────────────────────────────────────────────────────────────
-- warehouse  (branch)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.warehouse (
  id          bigint generated by default as identity not null,
  company_id  bigint                     not null,
  name        character varying(255)     not null,
  reference_no character varying(50)     not null default '',
  code        character varying(50)      null,
  address     text                       null,
  phone       character varying(50)      null,
  is_default  boolean                    not null default false,
  is_active   boolean                    not null default true,
  created_at  timestamp with time zone   not null default now(),
  updated_at  timestamp with time zone   not null default now(),

  constraint warehouse_pkey
    primary key (id),
  constraint warehouse_company_id_fkey
    foreign key (company_id) references public.company (id) on delete cascade
) tablespace pg_default;

create index if not exists warehouse_company_id_idx on public.warehouse (company_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- stock_location
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.stock_location (
  id          bigint generated by default as identity not null,
  branch_id   bigint                     not null,
  name        character varying(255)     not null,
  code        character varying(50)      null,
  description text                       null,
  is_default  boolean                    not null default false,
  is_active   boolean                    not null default true,
  created_at  timestamp with time zone   not null default now(),
  updated_at  timestamp with time zone   not null default now(),

  constraint stock_location_pkey
    primary key (id),
  constraint stock_location_branch_id_fkey
    foreign key (branch_id) references public.warehouse (id) on delete cascade
) tablespace pg_default;

create index if not exists stock_location_branch_id_idx on public.stock_location (branch_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- user_branch  (user ↔ warehouse membership + role)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.user_branch (
  user_id    uuid                   not null,
  branch_id  bigint                 not null,
  role       character varying(20)  not null default 'staff',

  constraint user_branch_pkey
    primary key (user_id, branch_id),
  constraint user_branch_user_id_fkey
    foreign key (user_id) references auth.users (id) on delete cascade,
  constraint user_branch_branch_id_fkey
    foreign key (branch_id) references public.warehouse (id) on delete cascade,
  constraint user_branch_role_check
    check (role in ('owner', 'manager', 'staff', 'viewer'))
) tablespace pg_default;
