create table public.inventory_item_category (
  id bigint generated by default as identity not null,
  name character varying not null default ''::character varying,
  reference_no character varying not null default ''::character varying,
  company_id bigint null,
  user_id uuid null,
  constraint inventory_item_category_pkey primary key (id),
  constraint inventory_item_category_company_id_fkey foreign KEY (company_id) references company (id),
  constraint inventory_item_category_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;



-- ─────────────────────────────────────────────────────────────────────────────
-- warehouse  (branch)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.warehouse (
  id          bigint generated by default as identity not null,
  company_id  bigint                     not null,
  name        character varying(255)     not null,
  reference_no character varying(50)     not null default '',
  code        character varying(50)      null,
  address     text                       null,
  phone       character varying(50)      null,
  is_default  boolean                    not null default false,
  is_active   boolean                    not null default true,
  created_at  timestamp with time zone   not null default now(),
  updated_at  timestamp with time zone   not null default now(),

  constraint warehouse_pkey
    primary key (id),
  constraint warehouse_company_id_fkey
    foreign key (company_id) references public.company (id) on delete cascade
) tablespace pg_default;

create index if not exists warehouse_company_id_idx on public.warehouse (company_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- warehouse_location
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.warehouse_location (
  id          bigint generated by default as identity not null,
  warehouse_id bigint                     not null,
  name        character varying(255)     not null,
  code        character varying(50)      null,
  description text                       null,
  is_default  boolean                    not null default false,
  is_active   boolean                    not null default true,
  created_at  timestamp with time zone   not null default now(),
  updated_at  timestamp with time zone   not null default now(),

  constraint warehouse_location_pkey
    primary key (id),
  constraint warehouse_location_warehouse_id_fkey
    foreign key (warehouse_id) references public.warehouse (id) on delete cascade
) tablespace pg_default;

create index if not exists warehouse_location_warehouse_id_idx on public.warehouse_location (warehouse_id);
