-- ============================================================================
-- Authorization Framework — per-action grants, tenant-scoped RBAC, audit trail.
--
-- The backend enforced no authorization: role_module_permission stored only 5
-- CRUD flags per (role, module) and nothing read them. This migration lays the
-- data foundation for a reusable framework:
--   1. role_module_action_permission — the new source of truth (role × module ×
--      action), tenant-scoped, seeded losslessly from the existing CRUD flags.
--   2. company_id on role_module_permission — structurally fixes the
--      role.updatePermissions cross-company IDOR.
--   3. authorization_event — append-only denial/sensitive-access audit log.
--   4. get_user_modules extended to also return the granted action list per
--      module (the 5 booleans stay, so the current frontend is unaffected).
--
-- Additive and idempotent. No grants are lost; no behavior changes until the
-- application framework (next phase) starts calling requirePermission.
-- ============================================================================

-- ── 1. Tenant-scope the legacy flag table (fixes the IDOR structurally) ─────
ALTER TABLE public.role_module_permission
    ADD COLUMN IF NOT EXISTS company_id bigint REFERENCES public.company (id) ON DELETE CASCADE;

UPDATE public.role_module_permission rmp
   SET company_id = r.company_id
  FROM public.roles r
 WHERE r.id = rmp.role_id
   AND rmp.company_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_role_module_permission_company
    ON public.role_module_permission (company_id);

-- ── 2. Per-action grant table (new source of truth) ─────────────────────────
CREATE TABLE IF NOT EXISTS public.role_module_action_permission (
    id          bigint generated by default as identity primary key,
    role_id     bigint  not null references public.roles (id)   on delete cascade,
    module_id   bigint  not null references public.modules (id) on delete cascade,
    company_id  bigint  not null references public.company (id) on delete cascade,
    action      text    not null,
    granted     boolean not null default true,
    created_by  uuid    references public.profiles (id) on delete set null,
    updated_by  uuid    references public.profiles (id) on delete set null,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    constraint uq_rmap_role_module_action unique (role_id, module_id, action)
);

CREATE INDEX IF NOT EXISTS idx_rmap_company_role ON public.role_module_action_permission (company_id, role_id);
CREATE INDEX IF NOT EXISTS idx_rmap_module_action ON public.role_module_action_permission (module_id, action);

-- keep updated_at fresh (shared trigger fn from the audit framework)
DROP TRIGGER IF EXISTS trg_role_module_action_permission_updated_at ON public.role_module_action_permission;
CREATE TRIGGER trg_role_module_action_permission_updated_at
    BEFORE UPDATE ON public.role_module_action_permission
    FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

ALTER TABLE public.role_module_action_permission ENABLE ROW LEVEL SECURITY;

-- ── 3. Seed the grant table from the existing CRUD flags (lossless) ─────────
-- Each true flag becomes an action row. Re-runnable via ON CONFLICT.
INSERT INTO public.role_module_action_permission (role_id, module_id, company_id, action, granted)
SELECT rmp.role_id, rmp.module_id, coalesce(rmp.company_id, r.company_id), a.action, true
FROM public.role_module_permission rmp
JOIN public.roles r ON r.id = rmp.role_id
CROSS JOIN LATERAL (
    VALUES ('view', rmp.can_view), ('create', rmp.can_create),
           ('update', rmp.can_update), ('delete', rmp.can_delete),
           ('export', rmp.can_export)
) AS a(action, flag)
WHERE a.flag = true
  AND coalesce(rmp.company_id, r.company_id) IS NOT NULL
ON CONFLICT (role_id, module_id, action) DO NOTHING;

-- ── 3b. Seed EXTENDED actions from a base capability (preserve behavior) ────
-- post/approve/prepare/count/complete/close derive from can_update; void/cancel
-- from can_delete. This keeps existing document flows working the moment
-- enforcement turns on, while the per-action table now allows finer control
-- (e.g. later granting 'post' without 'update'). Re-runnable.
INSERT INTO public.role_module_action_permission (role_id, module_id, company_id, action, granted)
SELECT rmp.role_id, rmp.module_id, coalesce(rmp.company_id, r.company_id), m.action, true
FROM public.role_module_permission rmp
JOIN public.roles r    ON r.id  = rmp.role_id
JOIN public.modules mo ON mo.id = rmp.module_id
JOIN (VALUES
    ('/inventory/receipts',     'post',     'update'),
    ('/inventory/receipts',     'void',     'delete'),
    ('/inventory/stock_adjust', 'post',     'update'),
    ('/inventory/stock_adjust', 'void',     'delete'),
    ('/inventory/stock_count',  'prepare',  'update'),
    ('/inventory/stock_count',  'count',    'update'),
    ('/inventory/stock_count',  'approve',  'update'),
    ('/inventory/stock_count',  'complete', 'update'),
    ('/inventory/stock_count',  'cancel',   'delete'),
    ('/sale/delivery-note',     'post',     'update'),
    ('/sale/delivery-note',     'void',     'delete'),
    ('/finances/invoice',       'post',     'update'),
    ('/finances/invoice',       'approve',  'update'),
    ('/finances/invoice',       'cancel',   'delete'),
    ('/finances/payment',       'post',     'update'),
    ('/finances/payment',       'cancel',   'delete'),
    ('/sale/order',             'close',    'update'),
    ('/sale/order',             'cancel',   'delete')
) AS m(module_key, action, base_cap) ON mo.key = m.module_key
WHERE coalesce(rmp.company_id, r.company_id) IS NOT NULL
  AND ((m.base_cap = 'update' AND rmp.can_update = true)
    OR (m.base_cap = 'delete' AND rmp.can_delete = true))
ON CONFLICT (role_id, module_id, action) DO NOTHING;

-- ── 4. Authorization audit trail (append-only) ──────────────────────────────
CREATE TABLE IF NOT EXISTS public.authorization_event (
    id             bigint generated by default as identity primary key,
    user_id        uuid,
    company_id     bigint,
    permission_key text,
    module         text,
    action         text,
    decision       text not null,          -- 'denied' | 'allowed_sensitive'
    reason         text,
    route          text,
    method         text,
    ip             text,
    created_at     timestamptz not null default now(),
    constraint chk_authz_event_decision check (decision in ('denied','allowed_sensitive'))
);

CREATE INDEX IF NOT EXISTS idx_authz_event_company_time ON public.authorization_event (company_id, created_at desc);
CREATE INDEX IF NOT EXISTS idx_authz_event_user_time    ON public.authorization_event (user_id, created_at desc);

ALTER TABLE public.authorization_event ENABLE ROW LEVEL SECURITY;

-- ── 5. Extend get_user_modules to also return granted actions per module ────
-- The 5 booleans are unchanged (existing frontend keeps working); `actions` is
-- the union of granted actions across the caller's roles for the company, used
-- by the new useCan() gating and the backend resolver.
DROP FUNCTION IF EXISTS get_user_modules(uuid, int);

CREATE FUNCTION get_user_modules(p_user_id uuid, p_company_id int)
RETURNS TABLE (
    id               int,
    key              text,
    label            text,
    path             text,
    component        text,
    parent_id        int,
    icon             text,
    sort_order       int,
    is_active        bool,
    type             text,
    is_initial_data  bool,
    can_view         bool,
    can_create       bool,
    can_update       bool,
    can_delete       bool,
    can_export       bool,
    actions          text[]
)
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
    WITH my_roles AS (
        SELECT role_id FROM user_role
        WHERE user_id = p_user_id AND company_id = p_company_id
    )
    SELECT
        mol.id, mol.key, mol.label, mol.path, mol.component, mol.parent_id,
        mol.icon, mol.sort_order, mol.is_active, mol.type, mol.is_initial_data,
        BOOL_OR(COALESCE(pem.can_view,   false)) AS can_view,
        BOOL_OR(COALESCE(pem.can_create, false)) AS can_create,
        BOOL_OR(COALESCE(pem.can_update, false)) AS can_update,
        BOOL_OR(COALESCE(pem.can_delete, false)) AS can_delete,
        BOOL_OR(COALESCE(pem.can_export, false)) AS can_export,
        COALESCE(
            (SELECT array_agg(DISTINCT ap.action)
               FROM role_module_action_permission ap
              WHERE ap.module_id = mol.id
                AND ap.granted = true
                AND ap.role_id IN (SELECT role_id FROM my_roles)),
            ARRAY[]::text[]
        ) AS actions
    FROM modules mol
    LEFT JOIN role_module_permission pem
           ON pem.module_id = mol.id
          AND pem.role_id IN (SELECT role_id FROM my_roles)
    WHERE mol.is_active = true
    GROUP BY mol.id, mol.key, mol.label, mol.path, mol.component,
             mol.parent_id, mol.icon, mol.sort_order, mol.is_active,
             mol.type, mol.is_initial_data
    ORDER BY mol.sort_order ASC;
$$;
