create table public.inventory_item_category (
  id bigint generated by default as identity not null,
  name character varying not null default ''::character varying,
  reference_no character varying not null default ''::character varying,
  company_id bigint null,
  user_id uuid null,
  constraint inventory_item_category_pkey primary key (id),
  constraint inventory_item_category_company_id_fkey foreign KEY (company_id) references company (id),
  constraint inventory_item_category_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;
