
-- ─────────────────────────────────────────────────────────────────────────────
-- inventory_item
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.inventory_item (
    id                 bigint generated by default as identity not null,
    name               character varying(255)    not null,
    reference_no       character varying(100)    null,
    sku                character varying(100)    null,
    description        text                      null,
    item_class         character varying(20)     not null default 'stock',

    -- Pricing
    price              numeric(15, 4)            not null default 0,
    min_price          numeric(15, 4)            null,
    max_price          numeric(15, 4)            null,
    cost               numeric(15, 4)            null,

    -- Flags
    is_variant         boolean                   not null default false,
    is_discount        boolean                   not null default false,
    is_sellable boolean not null default false,
    is_warranty boolean not null default false,
    is_returnable boolean not null default false,
    -- Media & extras
    images_url         text[]                    null,
    warranty_duration  character varying(100)    null,

    -- Relations
    category_id        bigint                    null,

    -- Tenant
    company_id         bigint                    null,
    user_id            uuid                      null,

    created_at         timestamp with time zone  not null default now(),
    writed_at          timestamp with time zone  not null default now(),

    constraint inventory_item_pkey
        primary key (id),
    constraint inventory_item_item_class_check
        check (item_class in ('stock', 'non_stock', 'service')),
    constraint inventory_item_price_check
        check (min_price is null or max_price is null or min_price <= max_price),
    constraint inventory_item_category_id_fkey
        foreign key (category_id) references public.inventory_item_category (id),
    constraint inventory_item_company_id_fkey
        foreign key (company_id) references public.company (id) on delete cascade,
    constraint inventory_item_user_id_fkey
        foreign key (user_id) references auth.users (id)
) tablespace pg_default;
-- ─────────────────────────────────────────────────────────────────────────────
-- inventory_item_uom
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.inventory_item_uom (
    id          bigint generated by default as identity not null,
    reference_no character varying(100)    null,
    name        character varying(100)    not null,
    display_name character varying(20)     null,
    company_id  bigint                    null,
    item_id     bigint                    null,
    user_id     uuid                      null,
    created_at  timestamp with time zone  not null default now(),
    writed_at   timestamp with time zone  not null default now(),
    constraint inventory_item_uom_pkey
        primary key (id),
    constraint inventory_item_uom_company_id_fkey
        foreign key (company_id) references public.company (id) on delete cascade,
    constraint inventory_item_uom_item_id_fkey
        foreign key (item_id) references public.inventory_item (id) on delete cascade,
    constraint inventory_item_uom_user_id_fkey
        foreign key (user_id) references auth.users (id)
) tablespace pg_default;

create index if not exists inventory_item_uom_company_id_idx on public.inventory_item_uom (company_id);



create index if not exists inventory_item_company_id_idx  on public.inventory_item (company_id);
create index if not exists inventory_item_category_id_idx on public.inventory_item (category_id);
create index if not exists inventory_item_item_class_idx  on public.inventory_item (item_class);
create index if not exists inventory_item_name_idx        on public.inventory_item using gin (to_tsvector('simple', name));

-- ─────────────────────────────────────────────────────────────────────────────
-- inventory_item_balance  (qty per item per location)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.inventory_item_balance (
    id          bigint generated by default as identity not null,
    item_id     bigint                    not null,
    location_id bigint                    not null,
    total_balance    numeric(15, 4)            not null default 0,
    available_balance numeric(15, 4)            not null default 0,
    company_id  bigint                    null,
    user_id     uuid                      null,
    created_at  timestamp with time zone  not null default now(),
    writed_at   timestamp with time zone  not null default now(),

    constraint inventory_item_balance_pkey
        primary key (id),
    constraint inventory_item_balance_item_location_uq
        unique (item_id, location_id),
    constraint inventory_item_balance_item_id_fkey
        foreign key (item_id) references public.inventory_item (id) on delete cascade,
    constraint inventory_item_balance_location_id_fkey
        foreign key (location_id) references public.warehouse_location (id) on delete cascade,
    constraint inventory_item_balance_company_id_fkey
        foreign key (company_id) references public.company (id) on delete cascade,
    constraint inventory_item_balance_user_id_fkey
        foreign key (user_id) references auth.users (id)
) tablespace pg_default;

create index if not exists inventory_item_balance_item_id_idx     on public.inventory_item_balance (item_id);
create index if not exists inventory_item_balance_location_id_idx on public.inventory_item_balance (location_id);
create index if not exists inventory_item_balance_company_id_idx  on public.inventory_item_balance (company_id);
create index if not exists inventory_item_balance_available_balance_idx on public.inventory_item_balance (available_balance);
