-- Create user_role reference / lookup table
create table public.user_role (
  id          bigint generated by default as identity not null,
  name        text   not null,
  description text   null,
  constraint user_role_pkey      primary key (id),
  constraint user_role_name_key  unique (name),
  constraint user_role_name_check check (name in ('supper_user', 'admin', 'staff', 'member'))
) TABLESPACE pg_default;

-- Seed the default roles
insert into public.user_role (name, description) values
  ('supper_user', 'Super user with full system access'),
  ('admin',       'Administrator with management access'),
  ('staff',       'Regular staff member'),
  ('member',      'Basic member with limited access');

-- Drop the old role constraint on profiles and replace with the new role set
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles
  add constraint profiles_role_check
  check (role in ('supper_user', 'admin', 'staff', 'member'));

-- Update default value for new signups to 'staff'
alter table public.profiles alter column role set default 'staff';
