
-- ─────────────────────────────────────────────────────────────────────────────
-- inventory_uom  (global unit-of-measure catalog per company)
-- NOTE: `wrated_at` (sic) is intentional — the live schema and uom.ts write it.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.inventory_uom (
    id           bigint generated by default as identity not null,
    created_at   timestamp with time zone  not null default now(),
    wrated_at    timestamp with time zone  null,
    name         character varying         not null,
    display_name character varying         not null,
    company_id   bigint                    not null,
    constraint inventory_uom_pkey
        primary key (id),
    constraint inventory_uom_company_id_fkey
        foreign key (company_id) references public.company (id) on delete set null
) tablespace pg_default;

-- ─────────────────────────────────────────────────────────────────────────────
-- inventory_item
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.inventory_item (
    id                 bigint generated by default as identity not null,
    name               character varying(255)    not null,
    reference_no       character varying(100)    null,
    sku                character varying(100)    null,
    description        text                      null,
    item_class         character varying(20)     not null default 'stock',

    -- Pricing
    price              numeric(15, 4)            not null default 0,
    min_price          numeric(15, 4)            null,
    max_price          numeric(15, 4)            null,
    cost               numeric(15, 4)            null,

    -- Flags
    is_variant         boolean                   not null default false,
    is_discount        boolean                   not null default false,
    is_sellable boolean not null default false,
    is_warranty boolean not null default false,
    is_returnable boolean not null default false,
    -- Extras
    warranty_duration  character varying(100)    null,

    -- Relations
    category_id        bigint                    null,

    -- Tenant
    company_id         bigint                    null,
    user_id            uuid                      null,

    created_at         timestamp with time zone  not null default now(),
    writed_at          timestamp with time zone  not null default now(),

    -- Base UOM + default receiving slot
    uom_id               bigint                  not null,
    default_warehouse_id bigint                  null,
    default_location_id  bigint                  null,

    constraint inventory_item_pkey
        primary key (id),
    constraint inventory_item_item_class_check
        check (item_class in ('stock', 'non_stock', 'service')),
    constraint inventory_item_price_check
        check (min_price is null or max_price is null or min_price <= max_price),
    constraint inventory_item_category_id_fkey
        foreign key (category_id) references public.inventory_item_category (id),
    constraint inventory_item_company_id_fkey
        foreign key (company_id) references public.company (id) on delete cascade,
    constraint inventory_item_user_id_fkey
        foreign key (user_id) references auth.users (id),
    constraint inventory_item_uom_id_fkey
        foreign key (uom_id) references public.inventory_uom (id) on update cascade on delete cascade,
    constraint fk_inventory_item_default_warehouse_id
        foreign key (default_warehouse_id) references public.warehouse (id),
    constraint fk_inventory_item_default_location_id
        foreign key (default_location_id) references public.warehouse_location (id)
) tablespace pg_default;
-- ─────────────────────────────────────────────────────────────────────────────
-- inventory_item_uom
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.inventory_item_uom (
    id          bigint generated by default as identity not null,
    reference_no character varying(100)    null,
    name        character varying(100)    not null,
    display_name character varying(20)     null,
    company_id  bigint                    null,
    item_id     bigint                    null,
    user_id     uuid                      null,
    created_at  timestamp with time zone  not null default now(),
    writed_at   timestamp with time zone  not null default now(),
    uom_id      bigint                    not null,
    conversion  real                      null,
    factor      real                      null,
    is_default  boolean                   not null,
    constraint inventory_item_uom_pkey
        primary key (id),
    constraint inventory_item_uom_company_id_fkey
        foreign key (company_id) references public.company (id) on delete cascade,
    constraint inventory_item_uom_item_id_fkey
        foreign key (item_id) references public.inventory_item (id) on delete cascade,
    constraint inventory_item_uom_user_id_fkey
        foreign key (user_id) references auth.users (id),
    constraint inventory_item_uom_uom_id_fkey
        foreign key (uom_id) references public.inventory_uom (id) on delete set null
) tablespace pg_default;

create index if not exists inventory_item_uom_company_id_idx on public.inventory_item_uom (company_id);



create index if not exists inventory_item_company_id_idx  on public.inventory_item (company_id);
create index if not exists inventory_item_category_id_idx on public.inventory_item (category_id);
create index if not exists inventory_item_item_class_idx  on public.inventory_item (item_class);
create index if not exists inventory_item_name_idx        on public.inventory_item using gin (to_tsvector('simple', name));

-- NOTE: the former `inventory_item_balance` table was removed — on-hand stock
-- lives in `inventory_balances`, maintained solely by the movement ledger
-- (20260701000000). No code references the old table.
